declare_args() {
  gnb_repo_dir = getenv("GNB_REPO_DIR")


  # toolchain flags
  dotfile_toolchain = "default"
  dotfile_asmflags = []
  dotfile_cflags = []
  dotfile_cflags_c = []
  dotfile_cflags_cc = []
  dotfile_arflags = []
  dotfile_ldflags = []
}

declare_args() {
  # scripts
  gnb_run = rebase_path("${gnb_repo_dir}/scripts/run.py")
  gnb_which = rebase_path("${gnb_repo_dir}/scripts/which.py")
}

# toolchain
set_default_toolchain("//:${dotfile_toolchain}")

template("declare_toolchain") {
  not_needed(invoker, "*")

  if (target_name == "gcc" || target_name == "default") {
    import("${gnb_repo_dir}/toolchains/gcc_toolchain.gni")
    gcc_toolchain("${dotfile_toolchain}") {
      asmflags = dotfile_asmflags
      cflags = dotfile_cflags
      cflags_c = dotfile_cflags_c
      cflags_cc = dotfile_cflags_cc
      arflags = dotfile_arflags
      ldflags = dotfile_ldflags
    }
  } else if (target_name == "clang") {
    import("${gnb_repo_dir}/toolchains/clang_toolchain.gni")
    clang_toolchain("${dotfile_toolchain}") {
      asmflags = dotfile_asmflags
      cflags = dotfile_cflags
      cflags_c = dotfile_cflags_c
      cflags_cc = dotfile_cflags_cc
      arflags = dotfile_arflags
      ldflags = dotfile_ldflags
    }
  } else {
    # try import toolchain from packages
    assert(false, "unknown toolchain: " + target_name)
  }
}

# package
import("${gnb_repo_dir}/dotfiles/package.gni")
