buildconfig = getenv("GNB_REPO_DIR") + "/dotfiles/BUILDCONFIG.gn"
script_executable = "python3"

export_compile_commands = ["*"]

default_args = {
  dotfile_toolchain = "gcc"

  dotfile_amsflags = []
  dotfile_cflags = [
    "-Os",
    "-DNDEBUG",
  ]
  dotfile_cflags_c = []
  dotfile_cflags_cc = []
  dotfile_arflags = []
  dotfile_ldflags = []
}
