assert(defined(gnb_repo_dir))
assert(defined(gnb_pkgs_dir))

declare_args() {
  gnb_which = rebase_path("${gnb_repo_dir}/gnbuild/scripts/which.py")
  gnb_pkgexec = rebase_path("${gnb_repo_dir}/gnbuild/scripts/pkgexec.py")
  gnb_pkgcopy = rebase_path("${gnb_repo_dir}/gnbuild/scripts/pkgcopy.py")
  gnb_pkgload = rebase_path("${gnb_repo_dir}/gnbuild/scripts/pkgload.py")
}

template("pkggroup") {
  not_needed(invoker, "*")

  group(target_name) {
    pkg_path = exec_script(gnb_pkgload,
                           [
                             target_name,
                             "--pkgsrc",
                             gnb_pkgs_dir,
                           ],
                           "string")

    public_deps = []
    if (defined(invoker.deps)) {
      foreach(dep, invoker.deps) {
        public_deps += [ "${pkg_path}/:${dep}" ]
      }
    } else {
      public_deps += [ "${pkg_path}/:default" ]
    }

    public_configs = []
    if (defined(invoker.configs)) {
      foreach(cfg, invoker.configs) {
        public_configs += [ "${pkg_path}/:${cfg}" ]
      }
    }
  }
}
