assert(defined(gnb_repo_dir))

declare_args() {
  if (host_os == "mac") {
    profile_toolchain = "clang"
  } else {
    profile_toolchain = "gcc"
  }
  profile_asmflags = []
  profile_cflags = []
  profile_cflags_c = []
  profile_cflags_cc = []
  profile_arflags = []
  profile_ldflags = []
}

set_default_toolchain("//:${profile_toolchain}")

template("declare_toolchain") {
  not_needed(invoker, "*")

  if (target_name == "gcc") {
    import("${gnb_repo_dir}/gnbuild/toolchains/gcc_toolchain.gni")
    gcc_toolchain("${profile_toolchain}") {
      asmflags = profile_asmflags
      cflags = profile_cflags
      cflags_c = profile_cflags_c
      cflags_cc = profile_cflags_cc
      arflags = profile_arflags
      ldflags = profile_ldflags
    }
  } else if (target_name == "clang") {
    import("${gnb_repo_dir}/gnbuild/toolchains/clang_toolchain.gni")
    clang_toolchain("${profile_toolchain}") {
      asmflags = profile_asmflags
      cflags = profile_cflags
      cflags_c = profile_cflags_c
      cflags_cc = profile_cflags_cc
      arflags = profile_arflags
      ldflags = profile_ldflags
    }
  } else if (target_name == "arm_none_eabi_gcc") {
    import("${gnb_repo_dir}/gnbuild/toolchains/arm_none_eabi_toolchain.gni")
    arm_none_eabi_toolchain("${profile_toolchain}") {
    }
  } else {
    # try import toolchain from packagess
    assert(false, "unknown toolchain: " + target_name)
  }
}
