assert(defined(gnb_repo_dir))

declare_args() {
  if (host_os == "mac") {
    profile_toolchain = "clang"
  } else {
    profile_toolchain = "gcc"
  }
}

set_default_toolchain("//:${profile_toolchain}")

if (profile_toolchain == "gcc") {
  import("${gnb_repo_dir}/gnbuild/toolchains/gcc_toolchain.gni")
  template("declare_toolchain") {
    not_needed(invoker, "*")
    gcc_toolchain(target_name) {
    }
  }
} else if (profile_toolchain == "clang") {
  import("${gnb_repo_dir}/gnbuild/toolchains/clang_toolchain.gni")
  template("declare_toolchain") {
    not_needed(invoker, "*")
    clang_toolchain(target_name) {
    }
  }
} else {
  toolchain_path = exec_script(gnb_pkg_load,
                               [
                                 profile_toolchain,
                                 "--pkgsrc",
                                 gnb_pkgs_dir,
                               ],
                               "string")
  import("${toolchain_path}/${profile_toolchain}.gni")
}
